/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#303033",
        "surface-tint": "#4b5e87",
        "on-secondary-container": "#00217a",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-variant": "#e3e2e6",
        "outline-variant": "#c5c6cf",
        "on-secondary-fixed": "#001453",
        "on-primary-fixed": "#031a40",
        "on-primary-fixed-variant": "#33466e",
        "primary-fixed": "#d8e2ff",
        "on-background": "#1b1b1e",
        "secondary": "#3755c3",
        "primary": "#000b25",
        "error-container": "#ffdad6",
        "surface": "#fbf8fc",
        "background": "#fbf8fc",
        "surface-dim": "#dbd9dd",
        "on-surface-variant": "#44474e",
        "primary-container": "#0b2147",
        "surface-container": "#efedf1",
        "surface-container-low": "#f5f3f7",
        "on-secondary-fixed-variant": "#173bab",
        "secondary-fixed-dim": "#b8c4ff",
        "outline": "#75777f",
        "secondary-fixed": "#dde1ff",
        "tertiary-fixed-dim": "#f7bd48",
        "on-primary-container": "#7789b5",
        "surface-container-high": "#e9e7eb",
        "on-tertiary-container": "#b28101",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f2f0f4",
        "tertiary-fixed": "#ffdea6",
        "secondary-container": "#708cfd",
        "on-surface": "#1b1b1e",
        "tertiary": "#120a00",
        "tertiary-container": "#2f1f00",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-container-highest": "#e3e2e6",
        "on-error": "#ffffff",
        "inverse-primary": "#b3c6f5",
        "primary-fixed-dim": "#b3c6f5",
        "on-tertiary-fixed-variant": "#5d4200",
        "surface-bright": "#fbf8fc",
        "on-tertiary-fixed": "#271900",
        "gold": "#b8860b",
        "emerald": "#059669",
        "navy": "#0b2147",
        "royal": "#1e40af",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        giant: "64px",
        "container-max": "1200px",
        gutter: "24px",
      },
      fontFamily: {
        display: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
